### ISSUE TITLE
Scan QR code function opens up Windows Snipping tool

### ISSUE THREAD

**Issue by Manwel72** [2fast-team/2fast#133] opened 2024-05-05 09:00 UTC
## Describe the bug

When trying to use the "scan QR code" button to scan a QR code on my brower, after 3 sec it opens up the Windows snipping tool instead, and thus cannot scan that QR code within the 2fast application. It used to work ok two months ago when I added some QR codes in the app, unsure of what has changed since.

## Steps to Reproduce

1. Using Windows 11
2. Go to Scan key-QR code
3. Click on on the button
4. The Windows snipping tool with open

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x ] Windows 11 23H2 Update (22631.3447)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment] 2024-05-05 17:46
The issue is related to a change by Microsoft. As workaround you can reset this configuration:
Go to "Settings → Apps → Default apps → Choose default apps by link type", and make sure that MS-SCREENCLIP is set to "Screen Snipping".
In the next app version I will change the QR code scanning for Windows 11 without dependence on the snipping tool.

**Comment by Manwel72** [comment] 2024-05-05 18:24
Thank you, that worked for me!

**Comment by mahengrui1** [comment] 2024-05-06 03:13
worked for me, but the snipping tool gets the screenshot at the same time

**Comment by jp-weber** [comment] 2024-07-28 15:41
Fixed with v1.3.0: https://github.com/2fast-team/2fast/releases/tag/v1.3.0 🎉

**Closed by jp-weber** 2024-07-28 15:41 UTC
