### ISSUE TITLE
data file cannot be selected and (re)loaded if moved to another folder/location

### ISSUE THREAD

**Issue by Mimisss** [2fast-team/2fast#68] opened 2023-05-15 16:02 UTC
## Describe the bug

If the data file is moved to another folder, the procedure to select and (re)load it cannot be completed. The "load data file" button remains inactive even after the data file is selected.

## Steps to Reproduce

1. Move .2fa file to another folder/location
2. Run 2fast, enter password to login
3. Click on 'Change file path' button
4. Click on 'Choose another datafile' button
5. Select the .2fa file and click on 'Open' button 
6. The 'Load data file' button is still deactivated and there is nothing else to do but Cancel

## Expected behavior

Once the .2fa file has been selected in step 6, you should be able to click on the 'Load data file' button.

## Screenshots

(the application does not allow screenshots to be taken on Windows 11)

## Environment

App Version(s): 1.2.6.0

Windows 11 Build Number:  22621.1702

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Insider Build ({build_number})
- [x] Windows 11 22H2

**Comment by jp-weber** [comment] 2023-05-15 18:35
Have you entered the password for the data file in the dialog? In my test it works as intended.

**Comment by Mimisss** [comment] 2023-05-16 12:28
Right. Well, it's a matter of UX, I guess. The size of the dialog needs considerably more space than the size of (my) application's window and there is no visual indication to suggest otherwise.

Here's the size of the application window:
![Screenshot 2023-05-16 152104](https://github.com/2fast-team/2fast/assets/10571178/8deaaaa8-d155-4a3c-8c54-264ba51117a0)

Inside that space, the 'Load data file' and 'Cancel' buttons are just below the horizontal line and it looks as if that's all there is to it, really.

**Comment by jp-weber** [comment] 2023-05-20 17:49
This is in fact partly a UI problem, as the height here was statically set at 400px. I have corrected this and automatically focused the password entry after selecting the folder.

Will be fixed in 1.2.7.

**Comment by jp-weber** [comment] 2023-09-17 18:55
Fixed in v1.2.7 (preview)

**Closed by jp-weber** 2023-09-17 18:55 UTC
Labels: bug🐛
