### ISSUE TITLE
Special HTML characters in QR code

### ISSUE THREAD

**Issue by Dimariqe** [2fast-team/2fast#80] opened 2023-08-31 20:38 UTC
## Describe the bug

The use of special HTML characters leads to a QR code recognition error

## Steps to Reproduce

otpauth://totp/blabla%2Fblabla:blabla?secret=MKRHRNFEXRYLEOTR&issuer=blabla%2Fblalba
![image](https://github.com/2fast-team/2fast/assets/3096178/4fe96859-96fd-41e2-bbf5-82c4f6afd6df)

## Expected behavior

Handling HTML characters and using them correctly, e.g. "%2F" = "/"

**Comment by jp-weber** [comment] 2023-09-03 15:51
Thank you for reporting the problem. The problem is primary based in the determination of the icon for the service. The html characters have been implemented without errors. The second error is based in the string of the QR code, the standard is ```otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example``` and not ```blabla/blabla:blabla?```

The error will be fixed with version 1.2.7.

![grafik](https://github.com/2fast-team/2fast/assets/10946850/45c41f68-50d2-4065-aa0d-d1e3608d577b)

**Comment by jp-weber** [comment] 2023-09-17 18:57
Fixed in v1.2.7 (preview).

**Closed by jp-weber** 2023-09-17 18:57 UTC
Labels: bug🐛
