### ISSUE TITLE
2fast freezes after creating .2fa file

### ISSUE THREAD

**Issue by jdieStrama** [2fast-team/2fast#71] opened 2023-06-01 10:46 UTC
## Describe the bug

After installing the app it freezes after creating a new .2fa file.
The file itself does exist afterwards but opening the app again results in freezing.

Only a reboot of the PC fixes this issue.

The App was installed manually with these steps:
- installung all dependencies
- installing the cert to the Local Machine (Root)
- installing the App (latest stable)

## Steps to Reproduce

1. Given the following environment
2. Install the App manually (not via MS Store; it is blocked at the company)
3. Create a new File
4. App freezes

## Expected behavior

It should not freeze after creating a new file :)

## Environment

App Version(s): 1.2.6

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [x] Windows 10 21H2 (19044.2965)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment] 2023-06-04 17:02
Which destination did you choose for the new data file?

The application cannot, for example, access C:/ and the individual Windows directories. I have introduced a dialog for error handling in this case in 1.2.7.

**Comment by jdieStrama** [comment] 2023-06-05 04:41
I've always saved the file in the user folder or in a subdirectory of it (Desktop or OneDrive for example). In some rare cases the app unfreezes. But most times it closes itself after a bit of time.

**Comment by jdieStrama** [comment] 2023-06-16 05:31
Any ideas?

**Comment by jp-weber** [comment] 2023-06-18 15:55
I cannot reproduce your problem. Can you install the installer from the MS Store? 
http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/521e8841-3aa1-48fd-9bf7-bd1e811d3fc8?P1=1687106487&P2=404&P3=2&P4=HQbD2eZ6pXQIl0A8ixpn0FgtbUvIBUOt2VAklVj3MNzqa5JzzGPfNHc7CLGiLM%2fb2QAv%2f5H9O32Ggv611NxQHw%3d%3d

**Comment by jdieStrama** [comment] 2023-06-19 07:19
> I cannot reproduce your problem. Can you install the installer from the MS Store? http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/521e8841-3aa1-48fd-9bf7-bd1e811d3fc8?P1=1687106487&P2=404&P3=2&P4=HQbD2eZ6pXQIl0A8ixpn0FgtbUvIBUOt2VAklVj3MNzqa5JzzGPfNHc7CLGiLM%2fb2QAv%2f5H9O32Ggv611NxQHw%3d%3d

Access Denied
You don't have permission to access "http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/521e8841-3aa1-48fd-9bf7-bd1e811d3fc8?" on this server.
Reference #18.8ca03717.1687159061.cedec51

**Comment by jp-weber** [comment] 2023-06-19 09:52
The link is expired, I will upload the store msixpackage later because I have currently only my smartphone available.

**Comment by jdieStrama** [comment] 2023-06-19 09:54
Ok.
I'll fetch all files from the store via adguard und try these files with its dependencies and let you know if it works

**Comment by jdieStrama** [comment] 2023-06-20 13:08
I've installed the .msixbundle file from the Store but no success.
As soon as I press the button for saving the 2fa file it freezes.

**Comment by jp-weber** [comment] 2023-06-20 17:29
Thank you for you feedback.

When the app crashes after the freeze, is there an error message with a description?

What I can do at this point is to create a debug version for you, which can write the error in a log, which you could then upload here.

**Comment by jdieStrama** [comment] 2023-06-21 08:16
No error.
The behaviour is hard to describe...
The window elements (Settings, Close, minimize) still respond to your mouse but everthing else is frozen.

I've sent you an invite via Linkedin. Maybe we can exchange better there.

**Comment by jp-weber** [comment] 2023-08-20 15:52
Could distribution via Intune using the Microsoft Store installation source be used as a workaround? If so, I would like to close the issue.

**Comment by jdieStrama** [comment] 2023-08-24 06:20
No luck with Intune. Installation fails as well

**Comment by jp-weber** [comment] 2023-09-17 18:51
I in my latest preview version I have changed the file system query https://github.com/2fast-team/2fast/blob/master/Project2FA.Shared/Services/DataService.cs#L278.

I could imagine that this might solve the problem:
https://github.com/2fast-team/2fast/releases/tag/v1.2.7-beta

**Closed** 2024-05-31 20:25 UTC
Labels: bug🐛, help wanted
